export const waterSystemConfig = {
  // Niveaux d'eau
  CRITICAL_WATER_LEVEL: 20,
  LOW_WATER_LEVEL: 30,
  HIGH_WATER_LEVEL: 80,
  VERY_HIGH_WATER_LEVEL: 90,

  // Qualité de l'eau
  CRITICAL_WATER_QUALITY: 50,
  LOW_WATER_QUALITY: 60,
  MEDIUM_WATER_QUALITY: 70,

  // Valeurs initiales
  INITIAL_DAM_WATER_LEVEL: 70,
  INITIAL_WATER_LEVEL: 50,
  INITIAL_PURIFIED_WATER: 100,
  INITIAL_POWER_GENERATED: 0,
  INITIAL_WATER_DISTRIBUTED: 50,
  INITIAL_IRRIGATION_WATER: 0,
  INITIAL_TREATED_WASTEWATER: 0,
  INITIAL_WATER_QUALITY: 90,
  INITIAL_FLOOD_RISK: 10,
  INITIAL_USER_CONSUMPTION: 0,
  INITIAL_GLACIER_VOLUME: 1000000,
  INITIAL_MELT_RATE: 0,
  INITIAL_WATER_FLOW: 0,
  INITIAL_DAM_WATER_VOLUME: 1000000,

  // Seuils de distribution d'eau
  LOW_WATER_DISTRIBUTION: 50,
  HIGH_WATER_DISTRIBUTION: 500,

  // Autres constantes
  THROTTLE_DELAY: 1000,
  DAILY_RESET_VALUE: 1000,

  // Flags de configuration
  enablePerformanceLogs: false,
  enableWaterSystemLogs: true,
  enableDetailedWaterSourceLogs: true,
};

export type WaterSystemConfig = typeof waterSystemConfig;
